#!/usr/bin/env python

"""
Each new term in the Fibonacci sequence is generated by adding the previous two terms. By starting with 1 and 2, the first 10 terms will be:

1, 2, 3, 5, 8, 13, 21, 34, 55, 89, ...

By considering the terms in the Fibonacci sequence whose values do not exceed four million, find the sum of the even-valued terms."""


def fib(limit):
    a = 1
    b = 2
    if a == 1 or a == 2:
        yield a
    while b < limit:
        a, b = b, a + b
        yield a
    return


def sum_evens(limit):
    s = 0
    for r in fib(limit):
        print (r,)
        if not r % 2:
            s += r
    return s

if __name__ == '__main__':
    for limit in (90, 4000000):
        print (limit)
        s = sum_evens(limit)
        print("The sum of even values of the fibonacci sequence up to %d is %d" % (limit, s))
